//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//
//     As alterações feitas neste arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Paginas
{


    public partial class CadPessoa
    {
        protected global::System.Web.UI.WebControls.Repeater rptTabela;
        protected global::System.Web.UI.WebControls.HiddenField PessoaSelecionados;
        protected global::System.Web.UI.WebControls.HiddenField hfpessoas;
    }
}
